<section class="header-hero-banner" style="background-image: url({{ url_for_lang(page.backgroundHeader) }})">
	<div class="container-fluid container-fluid--fixed">
		<h2 class="header-hero-banner__title">{{page.titleHeader}}</h2>
		<div class="header-hero-banner__content">
			<span class="header-hero-banner__desc">{{page.descHeaderFirst}}</span>
			<span class="header-hero-banner__desc">{{page.descHeaderSecond}}</span>
		</div>
	</div>
</section>
